version: "3.8"

services:
  app:
    container_name: airbnb-dev
    image: airbnb-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000